/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:401ae649-ec16-4b25-a7a3-7e45fb658d68",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_iFXpnOPZV",
    "aws_user_pools_web_client_id": "34d9hhlpld0rbprtv9o0htjecr",
    "oauth": {},
    "aws_content_delivery_bucket": "basicreact-20201218124509-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "http://basicreact-20201218124509-hostingbucket-dev.s3-website.ap-south-1.amazonaws.com"
};


export default awsmobile;
